spring.application.name: spring-boot-mongodb-multitenancy
config:
  multitenant:
    mongo:
      enabled: true
      properties:
        - tenant: tenant_a
          properties:
            uri: "mongodb://localhost:27014/"
            port: 27014
            database: tenant_a_db
        - tenant: tenant_b
          properties:
            uri: "mongodb://localhost:27014"
            port: 27017
            database: tenant_b_db
server:
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/employees
